### ISSUE TITLE
HTTPS redirection doesn't work for domain_redirects.conf

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomer-redirection#8]
For example, 

```
server {
        server_name     nptd.gov.sg *.nptd.gov.sg;
        return 301 https://www.strategygroup.gov.sg/;
}
```
But if you search for `https://nptd.gov.sg` it does not return the Strat Group website.

**Comment by prestonlimlianjie** [comment]
@kwajiehao this is a known issue - I think we shouldn’t support redirections on the isomer server for non-isomer sites.
